[WIP] FirstRelease
mendesbarreto/BSRescue pull request #1
Opened 2017-10-11 16:23 UTC by NatashaHMP

2017-10-13 20:29 UTC, mendesbarreto requested changes

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +public class Background : MonoBehaviour
Faltou dar um sealed na class

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +	private float BG_POSITION_Y = 0;
O prefixo BG é desnecessário, como vc já esta dentro do contexto da classe Background não é necessário especificar =) . Seria necessário especificar caso a classe estivesse em mais de um contexto.

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +	private void MoveBG()
O prefixo BG é desnecessário, como vc já esta dentro do contexto da classe Background não é necessário especificar =) . Seria necessário especificar caso a classe estivesse em mais de um contexto.

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +	private float VelocityBGInX ()
O prefixo BG é desnecessário, como vc já esta dentro do contexto da classe Background não é necessário especificar =) . Seria necessário especificar caso a classe estivesse em mais de um contexto.

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +	private float VelocityBGInX ()
Em nome de funções e métodos devemos evitar ter abreviação, já que o o tamanho do nome do método não impacta em performance do runtime ou compilador.

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +		return velocityBG;
o mesmo serve para nome de variáveis, quanto menos abreviações melhor.

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/Background.cs
> +public class Background : MonoBehaviour
O nome da classe Background, não está remetendo o que  classe faz, nesse contexto se olho o script vejo que ele seria uma classe que teria um background e as propriedades como nome, imagem, cor e etc... Normalmente nas frameworks o nome "Background" se remete a outro contexto, isso pode confundir o leitor do seu código. Pelo que entendi essa classe está bem separada e você conseguiu inserir o conceito de S do SOLID que é "Single Responsability" o que só falta para deixar ela tinindo é o nome, minha sugestão é MoveBackground, BackgroundPositionChanger, BackgroundPositioner, InfinityBackground, etc.. qualquer nome que remeta o que a ação do background.

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/CameraFollow.cs
> +		LoadResorces ();
Espaço entre o LoadResources e  o paracenteses

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/CameraFollow.cs
> +	private void LoadResorces ()
remover espaço entre o LoadResorces e o paracenteses

2017-10-13 20:29 UTC, mendesbarreto commented on Assets/Scripts/Board/CameraFollow.cs
> +		transform.position = new Vector3(LimitMoveXWithPlayer (),
emover espaço entre o LimitMoveXWithPlayer e o paracenteses

2017-10-13 21:56 UTC, mendesbarreto requested changes

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Constants.cs
> +public class Constants : MonoBehaviour
@NatashaHMP Você esqueceu de colocar sealed e não precisa ser MonoBehaviour

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Constants.cs
> +	private const string MAIN_MENU_SCENE_NAME = "MainMenu";
@NatashaHMP,  Eu tenho uma boa e uma Má notícia. 

A boa é que Foi isso mesmo que combinamos, perfeito, você pegou a ideia e mandou bala essa é a boa noticia, a má noticia é que existe alguns probleminhas com essa classe, vou resumir aqui mas qualquer coisa te ligo na segunda feira e te explico.

O primeiro problema é com o Nome da classe, pois só constantes não define exatamente o que sua classe contem, minha sugestão é que vc crie uma classe para cada tipo de constante, exemplo, LevelConstants, TagsConstants etc.. Ou você pode agrupar os tipos dentro de uma classe chamada Constants. segue os exemplos ======

Existem algumas sugestões Exemplo 1: 

```
// Separaria as constants assim, e não precisa herdar de MonoBehaviour, pois a classe não será processada pela,
// framework da unity
public sealed class SceneNameConstants {
    public const string LEVEL_SELECTION = "SelectLvl";
    public const string THREE_VALLEY = "MainLevel";
    public const string MENU = "Menu";
    public const string PAUSE = "Pause";
    public const string OPTIONS = "Options";
}

public sealed class TagsConstants {
    public const string PLAYER = "Player";
    public const string CAR = "Car";
    public const string MOTO_CROSS = "MotoCross";
    public const string PLAYER_LIFE = "PlayerLife";
    public const string UI_SCORE = "UIScore";
}

//Exemplo de como voce utilizaria == O nome da classe abaixo e so exemplo 
public class MenuSceneController {
    
    private void Update() {
        GotoScene(SceneNameConstants.THREE_VALLEY);
        GetGameObjectWithTag(TagsConstants.PLAYER);
    }
    
    private void GotoScene( string sceneName ) {
        //TODO: Faz ir para outra cena
    }

    private void GetGameObjectWithTag( string tagName ) {
        // TODO: Pega game object
    }
}

```

Sugestões Exemplo 2 a que acho mais bonita ahahahahah:

```
public sealed class Constants {
    public sealed class SceneName {
        public const string LEVEL_SELECTION = "SelectLvl";
        public const string THREE_VALLEY = "MainLevel";
        public const string MENU = "Menu";
        public const string PAUSE = "Pause";
        public const string OPTIONS = "Options";
    }
    
    public sealed class Tags {
        public const string PLAYER = "Player";
        public const string CAR = "Car";
        public const string MOTO_CROSS = "MotoCross";
        public const string PLAYER_LIFE = "PlayerLife";
        public const string UI_SCORE = "UIScore";
    }
}
//Exemplo de como voce utilizaria == O nome da classe abaixo e so exemplo 
public sealed class MenuSceneController {
    
    private void Update() {
        GotoScene(Constants.SceneName.LEVEL_SELECTION);
        GetGameObjectWithTag(Constants.Tags.PLAYER);
    }
    
    private void GotoScene( string sceneName ) {
        //TODO: Faz ir para outra cena
    }
    
    private void GetGameObjectWithTag( string tagName ) {
        // TODO: Pega game object
    }
}

```
O segundo é que já que estamos falando de constants então elas são imutáveis, ou seja, que ninguém pode alterar, o Getter é desnecessário, normalmente as constante são todas publicas e quem quiser pode acessar já que quando vc declara uma constant do tipo String ela já static por default.

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Fuel/FuelController.cs
> +		if (collider.gameObject.tag == Constants.instance.PlayerTagName)
@NatashaHMP Mudar Constants.instance.PlayerTagName para a especificação acima... que vai ficar:

` if (collider.gameObject.tag == Constants.TagConstants.PLAYER) `

ou

` if (collider.gameObject.tag == Constants.Tags.PLAYER) `

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Constants.cs
> +	private void Awake ()
Remover o Awake e a variável instance, depois que seguir as recomendações acima

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Player/Death.cs
> +		if (collision.gameObject.tag == Constants.instance.FloorTagName)
@NatashaHMP Mudar Constants.instance.FloorTagName para a especificação acima... que vai ficar:

if (collider.gameObject.tag == Constants.TagConstants.FLOOR)

ou

if (collider.gameObject.tag == Constants.Tags.FLOOR)

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Player/Death.cs
> +public class Death : MonoBehaviour
Faltou dar um sealed na class

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Player/InputController.cs
> +public class InputController : MonoBehaviour {
Faltou dar um sealed na class

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Player/PlayerGameStatus.cs
> +public class PlayerGameStatus : MonoBehaviour
Faltou dar um sealed na class

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Player/PlayerGameStatus.cs
> +		LoadResources ();
Remover os espaços entre o nome das funções e o parênteses

2017-10-13 21:56 UTC, mendesbarreto commented on Assets/Scripts/Player/PlayerLimitMove.cs
> +public class PlayerLimitMove : MonoBehaviour
Faltou dar um sealed na class

2017-10-16 10:50 UTC, gustavox13 requested changes

2017-10-16 10:50 UTC, gustavox13 commented on Assets/Scripts/Fuel/FuelController.cs
> +public class FuelController : MonoBehaviour
O nome da classe FuelControler da a entender que é o controlador de combustível do helicóptero, no caso o que aparecerá no Hud, que tal colocar, FuellLife ou FuellItem?

2017-10-16 10:50 UTC, gustavox13 commented on Assets/Scripts/Fuel/FuelController.cs
> +			Destroy (gameObject);
Evite usar o Destroy mais de uma vez em uma scene, é melhor usar o setActive, o Destroy acaba gerando travadas no jogo quando se trada de mobile, devido ao lixo que ele deixa na memoria do dispositivo.

2017-10-16 11:01 UTC, NatashaHMP commented on Assets/Scripts/Player/PlayerGameStatus.cs
> +		LoadResources ();
É automatico no MonoDevelop, mas eu tiro sim

2017-10-16 11:03 UTC, NatashaHMP commented on Assets/Scripts/Player/InputController.cs
> +public class InputController : MonoBehaviour {
Mas eu uso o InputController no PlayerController e no PlayerGameStatus

2017-10-16 15:47 UTC, mendesbarreto commented on Assets/Scripts/Player/InputController.cs
> +public class InputController : MonoBehaviour {
No problem... @NatashaHMP como vc utiliza de boas =)

2017-10-16 15:49 UTC, mendesbarreto commented on Assets/Scripts/Player/PlayerGameStatus.cs
> +		LoadResources ();
Mas mesmo sendo automatico, quando a classe não vai ser atrelada a um gameObject pode remover sem dó ahahahahaha

2017-10-16 17:10 UTC, NatashaHMP commented on Assets/Scripts/Constants.cs
> +public class Constants : MonoBehaviour
O sealed é necessário para esse caso mesmo eu usando ele em outros scripts?

2017-10-16 17:32 UTC, NatashaHMP commented on Assets/Scripts/Constants.cs
> +public class Constants : MonoBehaviour
ele = script Constants

2017-10-16 18:27 UTC, mendesbarreto commented on Assets/Scripts/Constants.cs
> +public class Constants : MonoBehaviour
Sim, 

O sealed é para ser sempre utilizando em classes que não devem ser Herdadas no sistema. Isso evita que os programadores façam extensão de uma classe que não foi desenvolvida para isso

2017-10-16 18:28 UTC, mendesbarreto commented on Assets/Scripts/Constants.cs
> +public class Constants : MonoBehaviour
A class Constants por exemplo não é uma classe para ser herdada apenas utilizada através das propriedades estáticas

2017-10-16 18:29 UTC, mendesbarreto commented on Assets/Scripts/Player/PlayerGameStatus.cs
> +		LoadResources ();
Acho que quando vc cria uma classe vc pode escolher se vai ser uma MonoBehaviour ou se vai ser uma classe normal, da uma olhada ai @NatashaHMP, acho que tem essa opção

2017-10-16 21:12 UTC, mendesbarreto requested changes

2017-10-16 21:12 UTC, mendesbarreto commented on Assets/Scripts/Constants.cs
> +}
@NatashaHMP sabe esse símbolo vermelhinho com a seta, quer dizer que o final do arquivo precisa de um enter para finalizar o arquivo...
É uma boa pratica de GIT que você sempre finalize o arquivo com um "ENTER/RETURN"

TODO: Inserir enter no final do arquivo

2017-10-16 21:12 UTC, mendesbarreto commented on Assets/Scripts/Player/PlayerGameStatus.cs
> +}
TODO: Inserir enter no final do arquivo

2017-11-03 12:52 UTC, gustavox13 approved these changes

2017-11-03 12:58 UTC, merged